### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by avenantsoftware** [acj/SSDPLib#1]
Could you perhaps provide an example of how this library works?

I want to use your code to find the ip address of a device in my network.

**Comment by acj** [comment]
@avenantsoftware I'm very sorry for not seeing this sooner. I hope you were able to find a solution.

The basic workflow as as follows:
 * Instantiate SSDP via `-[SSDP initWithDelegate:]` and pass in a delegate
 * Call `-startScanning` on the instance
 * Wait for the delegate callback to notify you that a service has been discovered
